### get all products

GET http://localhost:3000/api/products_1

### get a single product
GET http://localhost:3000/api/products/11

### create a single product
POST http://localhost:3000/api/products_1
Content-Type: application/json

{
  "name": "something name 2",
  "description": "something description"
}


### update a single product
PUT http://localhost:3000/api/products_1/18
Content-Type: application/json

{
  "description": "this is my new description123"
}

### delete a single product
DELETE http://localhost:3000/api/products/14